name: Trunk Code Quality setup
description: Set up dependencies for Trunk Code Quality

runs:
  using: composite
  steps:
    # Find tf working directory
    - name: Get terraform working directory
      id: tf-dir
      uses: tj-actions/changed-files@4918e1183080b35a085c91c8abc9e6adc4de61a1 # v42.1.0
      with:
        files: |
          tf/**/*.tf
          tf/**/*.tfvars
        dir_names: true

    # Install OpenTofu
    - name: Setup OpenTofu
      if: ${{ steps.tf-dir.outputs.all_changed_files != '' }}
      uses: opentofu/setup-opentofu@ae80d4ecaab946d8f5ff18397fbf6d0686c6d46a # v1.0.3

    # Initialise OpenTofu in the directory where terraform file have changed.
    - name: Initialise OpenTofu
      if: ${{ steps.tf-dir.outputs.all_changed_files != '' }}
      # TODO: The last run showed this in the logs:
      #! '/home/runner/work/.trunk/.trunk/tf/dev/vpc tf/dev/cdn tf/dev/vpc-peer'. No such file or directory
      #! So, we need to loop this somehow because a composite cannot use a matrix
      # working-directory: ${{ steps.tf-dir.outputs.all_changed_files }}
      shell: bash
      env:
        TF_DIRS: ${{ steps.tf-dir.outputs.all_changed_files }}
      run: |
        for dir in ${TF_DIRS}; do
          cd $GITHUB_WORKSPACE/$dir && tofu init --backend=false
        done
