name: PR Check
on:
  pull_request:
    types: [opened, edited, synchronize]

# Disable permissions for all available scopes
permissions: {}

jobs:
  validate-pr-title:
    name: Validate PR title
    permissions:
      pull-requests: write
    uses: 3ware/workflows/.github/workflows/pr-title.yaml@5cf20b3ba1cfdbe501dd2595dfb4ade9360641d8 # v3.1.0

  labeler:
    name: Apply labels
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Apply labels
        id: labeler
        uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
        with:
          sync-labels: true

      - name: Label not applied summary
        if: ${{ steps.labeler.outputs.new-labels && steps.labeler.outputs.all-labels == '""' }}
        run: |
          echo "# :negative_squared_cross_mark: Label(s) Not Applied to Pull Request >> $GITHUB_STEP_SUMMARY

      # TODO: Cater for multiple labels, there is only one at the moment so this works
      - name: Label applied summary
        if: ${{ steps.labeler.outputs.new-labels || steps.labeler.outputs.all-labels != '""' }}
        run: |
          echo "# :white_check_mark: Label(s) Applied to Pull Request" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## The following label(s) have been added to [#${{ github.event.pull_request.number }}](${{ github.event.pull_request.html_url }})" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          printf '%s\n' ${{ steps.labeler.outputs.all-labels }} >> $GITHUB_STEP_SUMMARY
