name: PR Check
on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]
    branches: [main]
  merge_group:
    types: [checks_requested]

# Disable permissions for all available scopes
permissions: {}

jobs:
  validate-pr-title:
    if: ${{ github.event_name == 'pull_request_target' }}
    name: Validate PR title
    permissions:
      contents: read
      pull-requests: write
    uses: 3ware/workflows/.github/workflows/pr-title.yaml@00ec3367b300beacba7ec64b1e4cc784d496d983 # v4.15.1

  dependency-review:
    if: ${{ github.event_name == 'pull_request_target' }}
    name: Dependency Review
    permissions:
      contents: read
      pull-requests: write
    uses: 3ware/workflows/.github/workflows/dependency-review.yaml@2f8001ae2c31dc22bac309ac1cc309d4cde3dff4 # v4.16.0

  enforce-all-checks:
    name: Checks
    permissions:
      checks: read
    uses: 3ware/workflows/.github/workflows/wait-for-checks.yaml@00ec3367b300beacba7ec64b1e4cc784d496d983 # v4.15.1
    secrets: inherit
