name: Release
run-name: ${{ github.event.workflow_run.display_title }}

on:
  workflow_run:
    workflows: [OpenTofu CI]
    types: [completed]
    branches: [main]

# Disable permissions for all available scopes
permissions: {}

jobs:
  semantic-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Release
    uses: 3ware/workflows/.github/workflows/release.yaml@30a4a9c7bc1b02f87df2196194d62668f554004e # v4.1.0
    secrets: inherit
