# This file is managed by terraform and should not be updated directly

name: Update terraform docs
on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - "**/*.tf"
      - "**/*.tfvars"
      - "**/*.hcl"

jobs:
  terraform-docs:
    uses: 3ware/workflows/.github/workflows/terraform-docs.yaml@v1.9.3
    secrets: inherit
