name: tfsec Code Analysis
on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - "**/*.tf"
      - "**/*.tfvars"
      - ".github/workflows/tfsec-pr.yaml"

jobs:
  tfsec-pr-commenter:
    permissions:
      pull-requests: write
      contents: read
    uses: 3ware/workflows/.github/workflows/tfsec-pr.yaml@v1.9.13
    secrets: inherit
    with:
      #* Use > over | for multi line when spaces are required.
      #* > replaces new line with spaces; 'folded style'
      #* | keeps new lines as new lines; 'literal style'
      #* - after > 'the chomping indicator' overrides the default behaviour
      #* 'clip' which adds a new line at the end, by stripping 'strip' it.
      tfsec_args: >-
        --tfvars-file=terraform.tfvars
