name: OpenTofu CI

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]
    paths:
      - tf/**/*.tf
      - tf/**.*.tfvars
  push:
    branches: [main]
    paths:
      - tf/**/*.tf
      - tf/**.*.tfvars

# Disable permissions for all available scopes
permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.repository }}
  cancel-in-progress: true

jobs:
  #TODO: Use find-terraform to get directory
  plan-and-apply-dev:
    name: Open Tofu CI
    permissions:
      actions: read # Required to download repository artifact.
      checks: write # Required to add status summary.
      contents: read # Required to checkout repository.
      id-token: write # Required to authenticate via OIDC.
      pull-requests: write # Required to add PR comment and label.
    uses: ./.github/workflows/tofu-ci-reuse.yaml
    with:
      environment: dev
      tf-directory: tf/dev/vpc
    secrets:
      backend-credentials: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}

  # terraform-docs:
  #   if: ${{ github.event_name == 'push' }}
  #   needs: plan-and-apply
  #   name: Terraform Docs
  #   uses: 3ware/workflows/.github/workflows/terraform-docs.yaml@22e03ff8b79ce67f4a5059d0d24c3d07d8d69b1b # v4.2.2
  #   secrets: inherit
