name: Checks
run-name: ${{ github.event_name == 'merge_group' && github.event.merge_group.head_commit.message || ''}}

on:
  pull_request:
    # Types not defined to ensure this action runs on all PR types
    branches: [main]
  merge_group:
    types: [checks_requested]

# Disable permissions for all available scopes
permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  enforce-all-checks:
    permissions:
      checks: read
    runs-on: ubuntu-latest
    # timeout removed because all plan / apply workflows may not be complete within this restriction
    #? Should it be left to run for the default [6 hours]?
    #timeout-minutes: 30
    steps:
      - name: GitHub Checks
        uses: poseidon/wait-for-status-checks@6988432d64ad3f9c2608db4ca16fded1b7d36ead # v0.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
